{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: ServiceMonitor
metadata:
  name: {{ include "interview-app.fullname" . }}
  labels:
    {{- include "interview-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
spec:
  selector:
    matchLabels:
      {{- include "interview-app.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: {{ include "interview-app.fullname" . }}-rules
  labels:
    {{- include "interview-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
spec:
  groups:
  - name: interview-app.rules
    rules:
    - alert: InterviewAppDown
      expr: up{job="{{ include "interview-app.fullname" . }}"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "Interview App is down"
        description: "Interview App has been down for more than 1 minute."
    - alert: InterviewAppHighErrorRate
      expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: "High error rate in Interview App"
        description: "Interview App is experiencing high error rate: {{ $value }} errors per second."
{{- end }}
