{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "interview-app.fullname" . }}
  labels:
    {{- include "interview-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: security
spec:
  podSelector:
    matchLabels:
      {{- include "interview-app.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: {{ .Values.networkPolicy.ingress.namespace }}
    - podSelector:
        matchLabels:
          {{- include "interview-app.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 53
    - protocol: UDP
      port: 53
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 80
{{- end }}
