apiVersion: v2
name: interview-app
description: A Helm chart for the interview application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
- flask
- python
- interview
- kubernetes
home: https://github.com/${{ github.repository }}
sources:
- https://github.com/${{ github.repository }}
maintainers:
- name: DevOps Team
  email: devops@example.com
