name: ArgoCD Status Check

on:
    workflow_dispatch:
    schedule:
        - cron: "*/5 * * * *" # Every 5 minutes

jobs:
    check-argocd-status:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup Kind
              uses: helm/kind-action@v1.8.0
              with:
                  cluster_name: gitops-cluster

            - name: Install ArgoCD
              run: |
                  # Install ArgoCD
                  kubectl create namespace argocd
                  kubectl apply -n argocd -f https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml

                  # Wait for ArgoCD to be ready
                  kubectl wait --for=condition=available --timeout=300s deployment/argocd-server -n argocd

                  # Install the application
                  kubectl apply -f argocd/application.yaml

                  # Wait for application to be ready
                  sleep 30

            - name: Check ArgoCD Application Status
              run: |
                  echo "=== ArgoCD Application Status ==="
                  kubectl get applications -n argocd -o wide

                  echo "=== Application Details ==="
                  kubectl describe application interview-app -n argocd

                  echo "=== Recent Sync Events ==="
                  kubectl get events -n argocd --sort-by='.lastTimestamp' | grep interview-app | tail -10

                  echo "=== Application Pods ==="
                  kubectl get pods -l app.kubernetes.io/name=interview-app -o wide

                  echo "=== Application Logs (Last 10 lines) ==="
                  kubectl logs -l app.kubernetes.io/name=interview-app --tail=10 || echo "No logs available"

                  echo "=== Deployment Image ==="
                  kubectl describe deployment interview-app | grep Image || echo "No deployment found"
